_base_ = 'tood_r101_fpn_12e_voc0712_cocofmt.py'
model = dict(
    backbone=dict(
        type='Res2Net',
        depth=101,
        scales=4,
        base_width=26,
        init_cfg=dict(
            type='Pretrained',
            checkpoint='open-mmlab://res2net101_v1d_26w_4s')))
work_dir = 'work_dirs/voc/tood/tood_r2_101_fpn_12e_voc0712_cocofmt'